-- Generated by Drizzle Kit + manually edited for partitioning.
-- DO NOT run drizzle-kit introspect after this file is applied.
-- See packages/database/README.md and RESEARCH.md Pitfall 1.

CREATE TABLE "products" (
  "id"           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name"         text NOT NULL,
  "distillery"   text NOT NULL,
  "age_years"    smallint,
  "volume_ml"    smallint NOT NULL,
  "category"     text NOT NULL,
  "region"       text,
  "cask_type"    text,
  "abv"          numeric(4,1),
  "image_url"    text,
  "description"  text,
  "review_score" numeric(4,1),
  "lwin_code"    text,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"   timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX "products_distillery_idx" ON "products" ("distillery");
CREATE INDEX "products_lwin_code_idx"  ON "products" ("lwin_code");

CREATE TABLE "retailers" (
  "id"                text PRIMARY KEY,
  "name"              text NOT NULL,
  "base_url"          text NOT NULL,
  "country"           char(2) NOT NULL,
  "currency"          char(3) NOT NULL,
  "scraper_type"      text NOT NULL,
  "catalog_url"       text NOT NULL,
  "cron_expression"   text NOT NULL DEFAULT '0 2 * * *',
  "affiliate_program" boolean NOT NULL DEFAULT false,
  "tos_status"        text NOT NULL DEFAULT 'ambiguous',
  "active"            boolean NOT NULL DEFAULT true,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "source_mappings" (
  "id"                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "canonical_product_id" uuid NOT NULL,
  "retailer_id"          text NOT NULL,
  "source_url"           text NOT NULL,
  "source_product_id"    text NOT NULL,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "source_mappings_canonical_product_id_fkey"
    FOREIGN KEY ("canonical_product_id") REFERENCES "products"("id") ON DELETE CASCADE,
  CONSTRAINT "source_mappings_retailer_id_fkey"
    FOREIGN KEY ("retailer_id") REFERENCES "retailers"("id")
);

CREATE UNIQUE INDEX "source_mappings_retailer_source_uniq"
  ON "source_mappings" ("retailer_id", "source_product_id");

-- MANUALLY EDITED: price_snapshots uses PARTITION BY RANGE.
-- Drizzle does not generate the partition clause — added here manually (RESEARCH.md Pitfall 1).
CREATE TABLE "price_snapshots" (
  "id"                    bigserial NOT NULL,
  "canonical_product_id"  uuid NOT NULL,
  "source_mapping_id"     uuid NOT NULL,
  "currency"              char(3) NOT NULL,
  "price_local"           numeric(10,2) NOT NULL,
  "price_usd"             numeric(10,2),
  "in_stock"              boolean NOT NULL DEFAULT true,
  "scraped_at"            timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "price_snapshots_pkey" PRIMARY KEY ("id", "scraped_at"),
  CONSTRAINT "price_snapshots_canonical_product_id_fkey"
    FOREIGN KEY ("canonical_product_id") REFERENCES "products"("id"),
  CONSTRAINT "price_snapshots_source_mapping_id_fkey"
    FOREIGN KEY ("source_mapping_id") REFERENCES "source_mappings"("id")
) PARTITION BY RANGE ("scraped_at");

CREATE TABLE "scraper_health" (
  "id"                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "retailer_id"               text NOT NULL,
  "last_scraped_at"           timestamp with time zone,
  "last_successful_scrape_at" timestamp with time zone,
  "last_scrape_status"        text,
  "success_rate_last_24h"     numeric(5,2),
  "consecutive_failures"      integer NOT NULL DEFAULT 0,
  "updated_at"                timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "scraper_health_retailer_id_fkey"
    FOREIGN KEY ("retailer_id") REFERENCES "retailers"("id")
);

CREATE UNIQUE INDEX "scraper_health_retailer_uniq" ON "scraper_health" ("retailer_id");

CREATE TABLE "dedup_review_queue" (
  "id"               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_a_id"     uuid NOT NULL,
  "product_b_id"     uuid NOT NULL,
  "similarity_score" numeric(4,3) NOT NULL,
  "status"           text NOT NULL DEFAULT 'pending',
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "dedup_review_queue_product_a_id_fkey"
    FOREIGN KEY ("product_a_id") REFERENCES "products"("id"),
  CONSTRAINT "dedup_review_queue_product_b_id_fkey"
    FOREIGN KEY ("product_b_id") REFERENCES "products"("id")
);

-- ============================================================
-- Manually appended (Drizzle does not generate any of the below)
-- DO NOT run drizzle-kit introspect after this point.
-- See packages/database/README.md and RESEARCH.md Pitfall 1.
-- ============================================================

-- Indexes on the parent table (cascade to partitions in PG 16)
CREATE INDEX "price_snapshots_product_scraped_idx"
  ON "price_snapshots" ("canonical_product_id", "scraped_at");
CREATE INDEX "price_snapshots_source_scraped_idx"
  ON "price_snapshots" ("source_mapping_id", "scraped_at");

-- Initial partitions: current month (May 2026) + next month (Jun 2026)
CREATE TABLE "price_snapshots_2026_05"
  PARTITION OF "price_snapshots"
  FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');

CREATE TABLE "price_snapshots_2026_06"
  PARTITION OF "price_snapshots"
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

-- DATA-03: Append-only enforcement at the SQL level.
-- REVOKE UPDATE/DELETE from the application role.
-- Superusers bypass this — production must use a non-superuser role.
DO $$
DECLARE
  app_role text := current_user;
BEGIN
  EXECUTE format('REVOKE UPDATE, DELETE ON TABLE price_snapshots FROM %I', app_role);
  EXECUTE format('GRANT  SELECT, INSERT ON TABLE price_snapshots TO %I',  app_role);
END$$;

-- DATA-05 / Phase 2 prerequisite: materialized view of best price per product (last 48h)
CREATE MATERIALIZED VIEW "current_best_prices" AS
SELECT
  p.id               AS product_id,
  MIN(ps.price_usd)  AS min_price_usd,
  MAX(ps.scraped_at) AS latest_scraped_at,
  COUNT(DISTINCT ps.source_mapping_id) FILTER (WHERE ps.in_stock) AS source_count
FROM products p
JOIN source_mappings sm ON sm.canonical_product_id = p.id
JOIN price_snapshots  ps ON ps.source_mapping_id   = sm.id
WHERE ps.scraped_at > now() - interval '48 hours'
GROUP BY p.id;

CREATE UNIQUE INDEX "current_best_prices_product_idx"
  ON "current_best_prices" (product_id);
